### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by locovna**

### CODE REVIEW

**Comment by Piliponful** [comment]
Congratulations! :tada:

**Comment by Piliponful** [comment]
Can I return my star now?

**Comment by Piliponful** [comment]
And why didn't you told hat you was writing a compiler... I can't imagine anything cooler. I'm myself thinking of doing one.
That maybe of some interest to you -
http://dev.stephendiehl.com/fun/

**Comment by locovna** [comment]
> Can I return my star now?

if required

> http://dev.stephendiehl.com/fun/

yes! If you check reference section, you'll find the link to this tutorial, but older, simplified version

**Comment by Piliponful** [comment]
>  you'll find the link to this tutorial
Oh. Now I see. Lol Just a few days ago I started thinking about writing one for a EVM.

**Comment by locovna** [comment]
I don't mind for any help or discussion 👌

**Comment by Piliponful** [comment]
> I don't mind for any help

What kind of help?
> discussion

I guess I will say if I feel like saying something... what i just said...

**Comment by Piliponful** [comment]
But I will look closely :eyes: at your blog. I'm still waiting for food reviews.

**Comment by locovna** [comment]
> for food reviews

Deal!

**Pull request merged**
